resources:
  - name: dwpdigital-cert-exporter
    type: registry-image-resource
    source:
      repository: dwpdigital/cert-exporter
    check_every: 5m

  - name: ecr-dwpdigital-cert-exporter-dev
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "cert-exporter"

  - name: ecr-dwpdigital-cert-exporter
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "cert-exporter"
      aws_role_arn: arn:aws:iam::((dataworks.aws_management_acc)):role/ci

jobs:
  - name: mirror-dwpdigital-cert-exporter-dev
    serial_groups: [cert-exporter]
    plan:
      - get: dwpdigital-cert-exporter
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-cert-exporter-dev
        params:
          image: "dwpdigital-cert-exporter/image.tar"
        attempts: 3

  - name: mirror-dwpdigital-cert-exporter
    serial_groups: [cert-exporter]
    plan:
      - get: dwpdigital-cert-exporter
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-cert-exporter
        params:
          image: "dwpdigital-cert-exporter/image.tar"
        attempts: 3
