jobs:
  - name: cert-exporter-pr
    plan:
      - get: cert-exporter-pr
        trigger: true
        version: every
      - put: cert-exporter-pr
        params:
          path: cert-exporter-pr
          status: pending
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          cert-exporter: cert-exporter-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          cert-exporter: cert-exporter-pr
        params:
          TF_WORKSPACE: "management"
          DETAILED_EXITCODE: ""
        on_failure:
          put: cert-exporter-pr
          params:
            path: cert-exporter-pr
            status: failure
        on_success:
          put: cert-exporter-pr
          params:
            path: cert-exporter-pr
            status: success
